### ISSUE TITLE
Crashed when trying to load it into forge server.

### ISSUE THREAD

**Issue by YuriNek0** [camcamcamcamcam/biome-backlog#2]
Trying to load it in multiplayer server and it crashed. Then I did some research about it and found that org/apache/commons/compress/utils/Lists is a client-side only dependency so no such library is gonna appears in forge server.

Here is the crash report.
```---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-02-12 19:46:50
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	at com.camcamcamcamcam.biome_backlog.capability.DeathTrackCapability.<init>(DeathTrackCapability.java:22) ~[biome_backlog-1.19.2-1.1.0.jar%23181!/:1.19.2-1.1.0] {re:classloading}
	at com.camcamcamcamcam.biome_backlog.register.ModEvents.onAttachEntityCapabilities(ModEvents.java:82) ~[biome_backlog-1.19.2-1.1.0.jar%23181!/:1.19.2-1.1.0] {re:classloading}
	at com.camcamcamcamcam.biome_backlog.register.__ModEvents_onAttachEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[biome_backlog-1.19.2-1.1.0.jar%23181!/:1.19.2-1.1.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:520) ~[forge-1.19.2-43.2.0-universal.jar%23254!/:?] {re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:514) ~[forge-1.19.2-43.2.0-universal.jar%23254!/:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:72) ~[forge-1.19.2-43.2.0-universal.jar%23254!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:67) ~[forge-1.19.2-43.2.0-universal.jar%23254!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:51) ~[forge-1.19.2-43.2.0-universal.jar%23254!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.initCapabilities(ServerLevel.java:1503) ~[server-1.19.2-20220805.130853-srg.jar%23249!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.entity_movement_tracking.ServerLevelAccessor,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:231) ~[server-1.19.2-20220805.130853-srg.jar%23249!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.entity_movement_tracking.ServerLevelAccessor,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:329) ~[server-1.19.2-20220805.130853-srg.jar%23249!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:300) ~[server-1.19.2-20220805.130853-srg.jar%23249!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:165) ~[server-1.19.2-20220805.130853-srg.jar%23249!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pfm-common.mixins.json:MixinDedicatedServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[server-1.19.2-20220805.130853-srg.jar%23249!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23249!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 657628160 bytes (627 MiB) / 2147483648 bytes (2048 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1700
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39950.91
	Virtual memory used (MB): 31204.57
	Swap memory total (MB): 7316.12
	Swap memory used (MB): 128.74
	JVM Flags: 2 total; -Xms2G -Xmx4G
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:smartbrainlib, mod:saturn (incompatible), mod:dynamiclightsreforged (incompatible), mod:create_things_and_misc, mod:paucal (incompatible), mod:botarium, mod:aoa3, mod:jei (incompatible), mod:biome_backlog, mod:teletubbies (incompatible), mod:mekanism, mod:sophisticatedcore (incompatible), mod:tslateffectslib, mod:citadel, mod:alexsmobs (incompatible), mod:sophisticatedbackpacks (incompatible), mod:buildinggadgets (incompatible), mod:create_dragon_lib, mod:starlight (incompatible), mod:bouncingballs_api (incompatible), mod:mekanismgenerators, mod:jeresources (incompatible), mod:hexcasting (incompatible), mod:cloth_config (incompatible), mod:forge, mod:pfm (incompatible), mod:twilightforest (incompatible), mod:supplementaries (incompatible), mod:jeimultiblocks, mod:ironchest (incompatible), mod:mcwbridges, mod:farmersdelight (incompatible), mod:terrablender, mod:moonlight (incompatible), mod:manure, mod:immersiveengineering (incompatible), mod:mekanismadditions, mod:jade (incompatible), mod:ae2 (incompatible), mod:nethersdelight (incompatible), mod:resourcefulconfig, mod:domum_ornamentum, mod:kotlinforforge (incompatible), mod:easy_villagers (incompatible), mod:flywheel (incompatible), mod:create, mod:railways (incompatible), mod:createplus (incompatible), mod:patchouli (incompatible), mod:blockui, mod:croptopia (incompatible), mod:create_sa, mod:collective, mod:earthmobsmod, mod:jecharacters (incompatible), mod:compactvoidminers (incompatible), mod:canary, mod:offlineskins (incompatible), mod:structurize, mod:multipiston, mod:resourcefullib (incompatible), mod:worldedit (incompatible), mod:minecolonies (incompatible), mod:mekanismtools, mod:architectury (incompatible), mod:otyacraftengine (incompatible), mod:mtr (incompatible), mod:iammusicplayer (incompatible), mod:appleskin, mod:aiimprovements, mod:fastfooddelight, mod:byg, mod:appmek (incompatible), mod:create_enchantment_industry (incompatible), mod:geckolib3 (incompatible), mod:caupona (incompatible), mod:createaddition (incompatible), mod:ad_astra (incompatible), Supplementaries Generated Pack
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.9.1
		lowcodefml@null
	Mod List: 
		SmartBrainLib-Forge-1.5.jar                       |SmartBrainLib                 |smartbrainlib                 |1.5                 |DONE      |Manifest: NOSIGNATURE
		saturn-mc1.19.2-0.0.1.jar                         |Saturn                        |saturn                        |0.0.1               |DONE      |Manifest: NOSIGNATURE
		dynamiclightsreforged-1.19.2_v1.4.0.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.19.2_v1.4.0       |DONE      |Manifest: NOSIGNATURE
		create_misc_and_things_1.19.2_1.1B.jar            |create: things and misc       |create_things_and_misc        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		paucal-forge-1.19.2-0.5.0.jar                     |PAUCAL                        |paucal                        |0.5.0               |DONE      |Manifest: NOSIGNATURE
		botarium-forge-1.19.2-1.8.2.jar                   |Botarium                      |botarium                      |1.8.2               |DONE      |Manifest: NOSIGNATURE
		AoA3-1.19.2-3.6.18.jar                            |Advent of Ascension           |aoa3                          |3.6.18              |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.5.2.1007.jar                  |Just Enough Items             |jei                           |11.5.2.1007         |DONE      |Manifest: NOSIGNATURE
		biome_backlog-1.19.2-1.1.0.jar                    |Biome Backlog                 |biome_backlog                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		teletubbies-1.19.1-10.1.0.jar                     |Teletubbies                   |teletubbies                   |10.1.0              |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.19.2-10.3.8.477.jar                    |Mekanism                      |mekanism                      |10.3.8              |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.19.2-0.5.38.203.jar           |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.38.203   |DONE      |Manifest: NOSIGNATURE
		TslatEffectsLib-forge-1.19.2-1.3.jar              |Tslat EffectsLib              |tslateffectslib               |1.3                 |DONE      |Manifest: NOSIGNATURE
		citadel-2.1.1-1.19.jar                            |Citadel                       |citadel                       |2.1.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.19.2-3.18.40.779.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.40.779  |DONE      |Manifest: NOSIGNATURE
		buildinggadgets-3.16.1-build.15+mc1.19.2.jar      |Building Gadgets              |buildinggadgets               |3.16.1-build.15+mc1.|DONE      |Manifest: NOSIGNATURE
		create_dragon_lib-1.19.2-1.1.2.jar                |Create: Dragon Lib            |create_dragon_lib             |1.1.2               |DONE      |Manifest: NOSIGNATURE
		starlight-1.1.1+forge.cf5b10b.jar                 |Starlight                     |starlight                     |1.1.1+forge.a3aea74 |DONE      |Manifest: NOSIGNATURE
		bouncing-balls-api-1.19.1-4.0.1.0.jar             |Bouncing Balls API            |bouncingballs_api             |4.0.1.0             |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.19.2-10.3.8.477 (1).jar      |Mekanism: Generators          |mekanismgenerators            |10.3.8              |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.19.2-1.2.1.193.jar          |Just Enough Resources         |jeresources                   |1.2.1.193           |DONE      |Manifest: NOSIGNATURE
		hexcasting-forge-1.19.2-0.10.3.jar                |Hex Casting                   |hexcasting                    |0.10.3              |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		paladin-furniture-mod-1.1.1-forge-mc1.19.jar      |Paladin's Furniture           |pfm                           |1.1.1               |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.19.2-4.2.1493-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1493            |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.2.35t.jar                |Supplementaries               |supplementaries               |1.19.2-2.2.35t      |DONE      |Manifest: NOSIGNATURE
		jeimultiblocks-1.19.2-0.0.3.jar                   |Just Enough Immersive Multiblo|jeimultiblocks                |0.0.3               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.19.2-14.2.7.jar                       |Iron Chests                   |ironchest                     |1.19.2-14.2.7       |DONE      |Manifest: NOSIGNATURE
		server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.0.6-mc1.19.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.6               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.2-2.0.1.136.jar           |TerraBlender                  |terrablender                  |2.0.1.136           |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.1.27-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.1.27       |DONE      |Manifest: NOSIGNATURE
		manure-1.19.2-2.0.jar                             |Manure                        |manure                        |2.0                 |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.19.2-9.1.2-159.jar         |Immersive Engineering         |immersiveengineering          |1.19.2-9.1.2-159    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		MekanismAdditions-1.19.2-10.3.8.477.jar           |Mekanism: Additions           |mekanismadditions             |10.3.8              |DONE      |Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.7.0.jar                       |Jade                          |jade                          |8.7.0               |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-forge-12.9.2.jar              |Applied Energistics 2         |ae2                           |12.9.2              |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.19.2-1.0.18.jar         |Resourcefulconfig             |resourcefulconfig             |1.0.18              |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.19-1.0.76-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.19-1.0.76-ALPHA   |DONE      |Manifest: NOSIGNATURE
		kffmod-3.9.1.jar                                  |Kotlin For Forge              |kotlinforforge                |3.9.1               |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.19.2-1.0.0.jar                   |Easy Villagers                |easy_villagers                |1.19.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.8.a-14.jar              |Flywheel                      |flywheel                      |0.6.8.a-14          |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |DONE      |Manifest: NOSIGNATURE
		Steam_Rails-1.19.2-1.0.6.jar                      |Create: Steam 'n Rails        |railways                      |1.19.2-1.0.6        |DONE      |Manifest: NOSIGNATURE
		createplus-1.19.2_v0.5.2a.jar                     |Create Plus                   |createplus                    |1.19.2_v0.5.2a      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |DONE      |Manifest: NOSIGNATURE
		blockui-1.19-0.0.67-ALPHA.jar                     |UI Library Mod                |blockui                       |1.19-0.0.67-ALPHA   |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |DONE      |Manifest: NOSIGNATURE
		create-stuff-additions1.19.2_v2.0.1c.jar          |Create Stuff & Additions      |create_sa                     |2.0.1               |DONE      |Manifest: NOSIGNATURE
		collective-1.19.2-6.43.jar                        |Collective                    |collective                    |6.43                |DONE      |Manifest: NOSIGNATURE
		EarthMobs-1.19.2-4.3.1.jar                        |Earth Mobs Mod                |earthmobsmod                  |1.19.2-4.3.1        |DONE      |Manifest: NOSIGNATURE
		jecharacters-1.19.2-4.3.9.jar                     |Just Enough Characters        |jecharacters                  |1.19.2-4.3.9        |DONE      |Manifest: NOSIGNATURE
		CompactVoidMiners-R1.19.2-1.20.jar                |Compact Void Miners           |compactvoidminers             |1.19.2-1.20         |DONE      |Manifest: NOSIGNATURE
		canary-mc1.19.2-0.1.8.jar                         |Canary                        |canary                        |0.1.8               |DONE      |Manifest: NOSIGNATURE
		OfflineSkins-1.19.2-v1.jar                        |OfflineSkins                  |offlineskins                  |1.19.2-v1           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		structurize-1.19.2-1.0.479-ALPHA.jar              |Structurize                   |structurize                   |1.19.2-1.0.479-ALPHA|DONE      |Manifest: NOSIGNATURE
		multipiston-1.19.2-1.2.25-ALPHA.jar               |Multi-Piston                  |multipiston                   |1.19.2-1.2.25-ALPHA |DONE      |Manifest: NOSIGNATURE
		resourcefullib-1.1.20.jar                         |Resourceful Lib               |resourcefullib                |1.1.20              |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.19.2-1.0.1210-BETA.jar             |MineColonies                  |minecolonies                  |1.19.2-1.0.1210-BETA|DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.19.2-10.3.8.477.jar               |Mekanism: Tools               |mekanismtools                 |10.3.8              |DONE      |Manifest: NOSIGNATURE
		architectury-6.4.62-forge.jar                     |Architectury                  |architectury                  |6.4.62              |DONE      |Manifest: NOSIGNATURE
		otyacraftengine-forge-mc1.19.2-3.2.0.jar          |Otyacraft Engine              |otyacraftengine               |3.2.0               |DONE      |Manifest: NOSIGNATURE
		Modern-Elevators-Escalators-forge-1.19.2-3.1.6.jar|Modern Elevators and Escalator|mtr                           |1.19.2-3.1.6        |DONE      |Manifest: NOSIGNATURE
		iammusicplayer-forge-mc1.19.2-3.19.5.jar          |Iam Music Player              |iammusicplayer                |3.19.5              |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.19.2-0.5.2.jar                  |AI-Improvements               |aiimprovements                |0.5.2               |DONE      |Manifest: NOSIGNATURE
		fastfooddelight-1.19-1.2.3.jar                    |https://github.com/akaneoMT/Fa|fastfooddelight               |1.19-1.2.3          |DONE      |Manifest: NOSIGNATURE
		Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar |Oh The Biomes You'll Go       |byg                           |2.0.0.13            |DONE      |Manifest: NOSIGNATURE
		Applied-Mekanistics-1.3.4.jar                     |Applied Mekanistics           |appmek                        |1.3.4               |DONE      |Manifest: NOSIGNATURE
		create_enchantment_industry-1.19.2-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.1.13              |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.38.jar                    |GeckoLib                      |geckolib3                     |3.1.38              |DONE      |Manifest: NOSIGNATURE
		caupona-1.19.2-0.2.2.jar                          |Caupona                       |caupona                       |1.19.2-0.2.2        |DONE      |Manifest: NOSIGNATURE
		createaddition-1.19.2-20221230a.jar               |Create Crafts & Additions     |createaddition                |1.19.2-20221230a    |DONE      |Manifest: NOSIGNATURE
		ad_astra-forge-1.19.2-1.12.2.jar                  |Ad Astra!                     |ad_astra                      |1.12.2              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b0fcfa77-ddd8-4f11-8a72-906580937b2e
	FML: 43.2
	Forge: net.minecraftforge:43.2.0```

**Comment by YuriNek0** [comment]
Fixed it by removing the dependency org.apache.commons.compress.utils.Lists. Unfortunately github is experiencing some problems that prevents me from forking the repo. I'll create my PR when github is back online.

**Comment by YuriNek0** [comment]
There you go, I created a PR for the fix.

**Comment by camcamcamcamcam** [comment]
I can't see where you fixed it; the only thing that's been pushed is the license file changes, as far as I can see.

**Comment by YuriNek0** [comment]
Sorry about that, maybe I forgot to add files in my commit. I’ll fix it in seconds.

Sent from my iPhone

On 13 Feb 2023, at 4:11 am, camcamcamcamcam ***@***.***> wrote:

﻿

I can't see where you fixed it; the only thing that's been pushed is the license file changes, as far as I can see.

**Comment by YuriNek0** [comment]
> 

Okay I have fixed my commit and force-pushed it. Now you can see it in my PR.

**Comment by camcamcamcamcam** [comment]
Thank you!
